apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    name: test
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
      - name: test
        image: gcr.io/apt-cycling-275313/test:latest
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  selector:
    name: test
  ports:
  - name: port1
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer



